In [2]:
import pandas as pd

data = [
    (101, "Rahul Sharma", "Data Engineering", 75000, "Hyderabad"),
    (102, "Priya Reddy", "AI Engineering", 85000, "Bangalore"),
    (103, "Amit Kumar", "Data Engineering", 65000, "Mumbai"),
    (104, "Sneha Patel", "Data Science", 95000, "Chennai"),
    (105, "Farhan Ali", "Cloud Engineering", 80000, "Delhi")
]

columns = [
    "employee_id",
    "name",
    "department",
    "salary",
    "city"
]

df = pd.DataFrame(data, columns=columns)
display(df.head())

   employee_id          name         department  salary       city
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
1          102   Priya Reddy     AI Engineering   85000  Bangalore
2          103    Amit Kumar   Data Engineering   65000     Mumbai
3          104   Sneha Patel       Data Science   95000    Chennai
4          105    Farhan Ali  Cloud Engineering   80000      Delhi

In [3]:
display(df[['employee_id', 'name']])

   employee_id          name
0          101  Rahul Sharma
1          102   Priya Reddy
2          103    Amit Kumar
3          104   Sneha Patel
4          105    Farhan Ali

In [4]:
display(df[['name', 'salary', 'city']])

           name  salary       city
0  Rahul Sharma   75000  Hyderabad
1   Priya Reddy   85000  Bangalore
2    Amit Kumar   65000     Mumbai
3   Sneha Patel   95000    Chennai
4    Farhan Ali   80000      Delhi

In [5]:
display(df.drop(columns=['city']))

   employee_id          name         department  salary
0          101  Rahul Sharma   Data Engineering   75000
1          102   Priya Reddy     AI Engineering   85000
2          103    Amit Kumar   Data Engineering   65000
3          104   Sneha Patel       Data Science   95000
4          105    Farhan Ali  Cloud Engineering   80000

In [6]:
display(df[df['salary'] > 70000])

   employee_id          name         department  salary       city
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
1          102   Priya Reddy     AI Engineering   85000  Bangalore
3          104   Sneha Patel       Data Science   95000    Chennai
4          105    Farhan Ali  Cloud Engineering   80000      Delhi

In [7]:
display(df[df['salary'] < 80000])

   employee_id          name        department  salary       city
0          101  Rahul Sharma  Data Engineering   75000  Hyderabad
2          103    Amit Kumar  Data Engineering   65000     Mumbai

In [8]:
display(df[df['city'] == 'Mumbai'])

   employee_id        name        department  salary    city
2          103  Amit Kumar  Data Engineering   65000  Mumbai

In [9]:
display(df[df['city'] == 'Bangalore'])

   employee_id         name      department  salary       city
1          102  Priya Reddy  AI Engineering   85000  Bangalore

In [10]:
display(df[df['department'] == 'Data Engineering'])

   employee_id          name        department  salary       city
0          101  Rahul Sharma  Data Engineering   75000  Hyderabad
2          103    Amit Kumar  Data Engineering   65000     Mumbai

In [11]:
display(df[df['department'] == 'AI Engineering'])

   employee_id         name      department  salary       city
1          102  Priya Reddy  AI Engineering   85000  Bangalore

In [12]:
display(df[(df['salary'] >= 70000) & (df['salary'] <= 90000)])

   employee_id          name         department  salary       city
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
1          102   Priya Reddy     AI Engineering   85000  Bangalore
4          105    Farhan Ali  Cloud Engineering   80000      Delhi

In [13]:
display(df[(df['city'] == 'Hyderabad') & (df['salary'] > 70000)])

   employee_id          name        department  salary       city
0          101  Rahul Sharma  Data Engineering   75000  Hyderabad

In [14]:
display(df[(df['city'] == 'Bangalore') | (df['city'] == 'Chennai')])

   employee_id         name      department  salary       city
1          102  Priya Reddy  AI Engineering   85000  Bangalore
3          104  Sneha Patel    Data Science   95000    Chennai

In [15]:
display(df[df['city'].isin(['Hyderabad', 'Mumbai', 'Delhi'])])

   employee_id          name         department  salary       city
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
2          103    Amit Kumar   Data Engineering   65000     Mumbai
4          105    Farhan Ali  Cloud Engineering   80000      Delhi

In [16]:
display(df[df['department'].isin(['Data Engineering', 'AI Engineering'])])

   employee_id          name        department  salary       city
0          101  Rahul Sharma  Data Engineering   75000  Hyderabad
1          102   Priya Reddy    AI Engineering   85000  Bangalore
2          103    Amit Kumar  Data Engineering   65000     Mumbai

In [17]:
display(df.sort_values(by='salary', ascending=True))

   employee_id          name         department  salary       city
2          103    Amit Kumar   Data Engineering   65000     Mumbai
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
4          105    Farhan Ali  Cloud Engineering   80000      Delhi
1          102   Priya Reddy     AI Engineering   85000  Bangalore
3          104   Sneha Patel       Data Science   95000    Chennai

In [18]:
display(df.sort_values(by='salary', ascending=False))

   employee_id          name         department  salary       city
3          104   Sneha Patel       Data Science   95000    Chennai
1          102   Priya Reddy     AI Engineering   85000  Bangalore
4          105    Farhan Ali  Cloud Engineering   80000      Delhi
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
2          103    Amit Kumar   Data Engineering   65000     Mumbai

In [19]:
display(df.sort_values(by='name'))

   employee_id          name         department  salary       city
2          103    Amit Kumar   Data Engineering   65000     Mumbai
4          105    Farhan Ali  Cloud Engineering   80000      Delhi
1          102   Priya Reddy     AI Engineering   85000  Bangalore
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
3          104   Sneha Patel       Data Science   95000    Chennai

In [20]:
display(df.sort_values(by=['city', 'salary']))

   employee_id          name         department  salary       city
1          102   Priya Reddy     AI Engineering   85000  Bangalore
3          104   Sneha Patel       Data Science   95000    Chennai
4          105    Farhan Ali  Cloud Engineering   80000      Delhi
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
2          103    Amit Kumar   Data Engineering   65000     Mumbai

In [21]:
df['bonus'] = df['salary'] * 0.10
display(df.head())

   employee_id          name         department  salary       city   bonus
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad  7500.0
1          102   Priya Reddy     AI Engineering   85000  Bangalore  8500.0
2          103    Amit Kumar   Data Engineering   65000     Mumbai  6500.0
3          104   Sneha Patel       Data Science   95000    Chennai  9500.0
4          105    Farhan Ali  Cloud Engineering   80000      Delhi  8000.0

In [22]:
df['tax'] = df['salary'] * 0.05
display(df.head())

,employee_id,name,department,salary,city,bonus,tax
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0

In [23]:
df['annual_salary'] = df['salary'] * 12
display(df.head())

,employee_id,name,department,salary,city,bonus,tax,annual_salary
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0,1140000
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000

In [24]:
df['salary_after_bonus'] = df['salary'] + df['bonus']
display(df.head())

,employee_id,name,department,salary,city,bonus,tax,annual_salary,salary_after_bonus
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000,82500.0
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000,93500.0
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000,71500.0
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0,1140000,104500.0
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000,88000.0

In [25]:
df.rename(columns={'salary': 'monthly_salary'}, inplace=True)
display(df.head())

,employee_id,name,department,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000,82500.0
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000,93500.0
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000,71500.0
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0,1140000,104500.0
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000,88000.0

In [26]:
df.rename(columns={'department': 'team'}, inplace=True)
display(df.head())

,employee_id,name,team,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000,82500.0
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000,93500.0
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000,71500.0
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0,1140000,104500.0
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000,88000.0

In [27]:
total_salary_payout = df['monthly_salary'].sum()
print(f"Total Salary Payout: ₹{total_salary_payout}")

Total Salary Payout: ₹400000

In [28]:
average_salary = df['monthly_salary'].mean()
print(f"Average Salary: ₹{average_salary}")

Average Salary: ₹80000.0

In [29]:
max_salary = df['monthly_salary'].max()
print(f"Maximum Salary: ₹{max_salary}")

Maximum Salary: ₹95000

In [30]:
min_salary = df['monthly_salary'].min()
print(f"Minimum Salary: ₹{min_salary}")

Minimum Salary: ₹65000

In [31]:
employee_count = df['employee_id'].count()
print(f"Total Employee Count: {employee_count}")

Total Employee Count: 5

In [32]:
employees_by_department = df['team'].value_counts()
print("Employees by Department:")
display(employees_by_department)

Employees by Department:

team
Data Engineering     2
AI Engineering       1
Data Science         1
Cloud Engineering    1
Name: count, dtype: int64

In [33]:
avg_salary_by_department = df.groupby('team')['monthly_salary'].mean()
print("Average Salary by Department:")
display(avg_salary_by_department)

Average Salary by Department:

team
AI Engineering       85000.0
Cloud Engineering    80000.0
Data Engineering     70000.0
Data Science         95000.0
Name: monthly_salary, dtype: float64

In [34]:
max_salary_by_department = df.groupby('team')['monthly_salary'].max()
print("Maximum Salary by Department:")
display(max_salary_by_department)

Maximum Salary by Department:

team
AI Engineering       85000
Cloud Engineering    80000
Data Engineering     75000
Data Science         95000
Name: monthly_salary, dtype: int64

In [35]:
min_salary_by_department = df.groupby('team')['monthly_salary'].min()
print("Minimum Salary by Department:")
display(min_salary_by_department)

Minimum Salary by Department:

team
AI Engineering       85000
Cloud Engineering    80000
Data Engineering     65000
Data Science         95000
Name: monthly_salary, dtype: int64

In [36]:
total_salary_by_department = df.groupby('team')['monthly_salary'].sum()
print("Total Salary by Department:")
display(total_salary_by_department)

Total Salary by Department:

team
AI Engineering        85000
Cloud Engineering     80000
Data Engineering     140000
Data Science          95000
Name: monthly_salary, dtype: int64

In [37]:
unique_departments = df['team'].unique()
print("Unique Departments:")
print(unique_departments)

Unique Departments:
['Data Engineering' 'AI Engineering' 'Data Science' 'Cloud Engineering']

In [38]:
unique_cities = df['city'].unique()
print("Unique Cities:")
print(unique_cities)

Unique Cities:
['Hyderabad' 'Bangalore' 'Mumbai' 'Chennai' 'Delhi']

In [39]:
count_unique_departments = df['team'].nunique()
print(f"Count of Unique Departments: {count_unique_departments}")

Count of Unique Departments: 4

In [40]:
top_3_highest_paid = df.nlargest(3, 'monthly_salary')
print("Top 3 Highest-Paid Employees:")
display(top_3_highest_paid)

Top 3 Highest-Paid Employees:

,employee_id,name,team,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0,1140000,104500.0
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000,93500.0
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000,88000.0

In [41]:
lowest_paid_employee = df.nsmallest(1, 'monthly_salary')
print("Lowest-Paid Employee:")
display(lowest_paid_employee)

Lowest-Paid Employee:

,employee_id,name,team,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000,71500.0

In [42]:
employees_start_with_R = df[df['name'].str.startswith('R')]
print("Employees whose names start with 'R':")
display(employees_start_with_R)

Employees whose names start with 'R':

,employee_id,name,team,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000,82500.0

In [43]:
employees_contain_a = df[df['name'].str.contains('a', case=False)]
print("Employees whose names contain 'a':")
display(employees_contain_a)

Employees whose names contain 'a':

,employee_id,name,team,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000,82500.0
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000,93500.0
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000,71500.0
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0,1140000,104500.0
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000,88000.0

In [44]:
employees_in_engineering = df[df['team'].str.contains('Engineering', case=False, na=False)]
print("Employees working in departments containing 'Engineering':")
display(employees_in_engineering)

Employees working in departments containing 'Engineering':

,employee_id,name,team,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000,82500.0
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000,93500.0
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000,71500.0
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000,88000.0

In [45]:
def categorize_salary(salary):
    if salary >= 85000:
        return 'High'
    elif salary >= 75000:
        return 'Medium'
    else:
        return 'Low'

df['salary_category'] = df['monthly_salary'].apply(categorize_salary)
display(df.head())

,employee_id,name,team,monthly_salary,city,bonus,tax,annual_salary,salary_after_bonus,salary_category
0,101,Rahul Sharma,Data Engineering,75000,Hyderabad,7500.0,3750.0,900000,82500.0,Medium
1,102,Priya Reddy,AI Engineering,85000,Bangalore,8500.0,4250.0,1020000,93500.0,High
2,103,Amit Kumar,Data Engineering,65000,Mumbai,6500.0,3250.0,780000,71500.0,Low
3,104,Sneha Patel,Data Science,95000,Chennai,9500.0,4750.0,1140000,104500.0,High
4,105,Farhan Ali,Cloud Engineering,80000,Delhi,8000.0,4000.0,960000,88000.0,Medium

In [46]:
salary_category_counts = df['salary_category'].value_counts()
print("Count of Employees in Each Salary Category:")
display(salary_category_counts)

Count of Employees in Each Salary Category:

salary_category
Medium    2
High      2
Low       1
Name: count, dtype: int64

In [49]:
final_report = df[['employee_id', 'name', 'team', 'monthly_salary', 'bonus', 'annual_salary']]
print("Final Report:")
display(final_report)

Final Report:

,employee_id,name,team,monthly_salary,bonus,annual_salary
0,101,Rahul Sharma,Data Engineering,75000,7500.0,900000
1,102,Priya Reddy,AI Engineering,85000,8500.0,1020000
2,103,Amit Kumar,Data Engineering,65000,6500.0,780000
3,104,Sneha Patel,Data Science,95000,9500.0,1140000
4,105,Farhan Ali,Cloud Engineering,80000,8000.0,960000